### ISSUE TITLE
Error rebuilding gh-pages site

### ISSUE THREAD

**Issue by ohsk** [urbanlaunchpad/surveyBuilder#1]
@buzoherbert @kuanb 
Here's what I found in terms of fixing the Validation issue noted in settings:

https://github.com/forfutureLLC/bara/issues/1#issuecomment-68589122

> This Error may have been caused by one of the following actions:
> 
> * Creating Organisation pages after creating the Project pages
> * Adding CNAME for a custom domain for the Organisation page
>
> This was fixed after:
> 1. deleting the gh-pages branch from the remote repository for the Project pages
> 2. re-create the gh-pages branch in the remote repository for the Project pages

![image](https://cloud.githubusercontent.com/assets/1689222/8587021/540d7c1a-25c4-11e5-99a1-b361d85981e1.png)

**Comment by kuanb** [comment]
thanks just for record since angular dev has been forked to my gh, the current build is sitting on kuanbutts.com/surveyBuilder/ gh-pages
