### ISSUE TITLE
Loop Questions: Error adding questions

### ISSUE THREAD

**Issue by acadhe** [urbanlaunchpad/surveyBuilder#15]
After Loop is created, it is not possible to add any type of question

**Comment by kuanb** [comment]
can you include a screen shot? 

when you choose loop, it makes a note that questions must be added in the loop logic
see warning:
![image](https://cloud.githubusercontent.com/assets/6053396/9320849/b4601ce4-452c-11e5-8ac5-06227f2fa4ce.png)

then here is the ux:
![image](https://cloud.githubusercontent.com/assets/6053396/9320865/e6acb004-452c-11e5-8190-66d15f0633e8.png)


that is the ux within the loop

does the solve the issue or is there another problem?

**Comment by kuanb** [comment]
since i havent seen any response and i think this is resolved, i am going to close. if issue is still present please open a new issue with screen caps of the area/point of issue
